[workspace]
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge", "bioconda"]
name = "gpr_sella_repro"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
git-subrepo = ">=0.4.3,<0.5"
python = "<3.13"
pip = ">=24.2,<25"
cmake = ">=3.30.5,<4"
meson = ">=1.6.0,<2"
cython = ">=3.0.11,<4"
ninja = ">=1.12.1,<2"
pkgconfig = ">=1.5.5,<2"
openblas = ">=0.3.28,<0.4"
highfive = ">=2.10.0,<3"
eigen = "==3.4.0"
fmt = "<=10"
spdlog = "<=1.14"
boost-cpp = ">=1.85.0,<2"
abseil-cpp = ">=20220623.0,<20220624"
pipx = ">=1.7.1,<2"
pre-commit = ">=4.0.1,<5"
cppcheck = ">=2.16.0,<3"
numpy = ">=2.1.2,<3"
cpplint = ">=1.6.0,<2"
clang-format = ">=19.1.2,<20"
ruff = ">=0.7.1,<0.8"
snakemake = ">=8.25.2,<9"
dvc = ">=3.56.0,<4"
rclone = ">=1.68.1,<2"
dvc-webdav = ">=3.0.0,<4"
openssl = ">=3.3.2,<4"
compilers = ">=1.8.0,<2"
pybind11 = ">=2.13.6,<3"
ipython = ">=8.31.0,<9"
h5py = ">=3.12.1,<4"
snakemake-executor-plugin-cluster-generic = ">=1.0.9,<2"
ripgrep = ">=14.1.1,<15"
openmpi = ">=5.0.6,<6"

[pypi-dependencies]
rgpycrumbs = { path = "./subrepos/rgpycrumbs", editable=true}
ase = { path = "./subrepos/ase", editable = true}
sella = { path = "./subrepos/sella", editable = true}

[activation]
scripts = ["scripts/env_setup.sh"]

[environments]
analysis = {features = ["useR", "plotPy"]}
# torch = {features = ["torch"]}
# intel = {features = ["onemkl"]}

[feature.useR]
platforms = ["linux-64"]

[feature.useR.dependencies]
r-unigd = ">=0.1.2,<0.2"
r-devtools = ">=2.4.5,<3"
r-svglite = ">=2.1.3,<3"
r-patchwork = ">=1.3.0,<2"
r-tidyverse = ">=2.0.0,<3"
r-httpgd = ">=1.3.1,<2"
r-lme4 = ">=1.1_35.5,<2"
r-lmertest = ">=3.1_3,<4"
r-brms = ">=2.22.0,<3"
r-cmdstanr = ">=0.8.1,<0.9"
cmdstan = ">=2.36.0,<3"
radian = ">=0.6.13,<0.7"
r-withr = ">=3.0.2,<4"
r-bridgesampling = ">=1.1_2,<2"
r-pak = ">=0.8.0.1,<0.9"
r-ggrepel = ">=0.9.6,<0.10"
r-tidybayes = ">=3.0.7,<4"
r-emmeans = "*"
r-ggthemes = ">=5.1.0,<6"
r-ggnewscale = ">=0.5.0,<0.6"
r-latex2exp = ">=0.9.6,<0.10"
r-cowplot = ">=1.1.3,<2"

[feature.plotPy]
platforms = ["linux-64"]

[feature.plotPy.dependencies]
cmcrameri = ">=1.9,<2"
matplotlib = ">=3.9.3,<4"

[feature.plotPy.pypi-dependencies]
pychumpchem = { path = "./subrepos/pychumpchem", editable=true}
chemparseplot = { path = "./subrepos/chemparseplot", editable=true}

[target.linux-64.dependencies]
mold = ">=2.36.0,<3"
