[project]
name = "gpr_optim"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
gtest = "1.14.0.*"
eigen = "3.4.0.*"
cmake = "3.27.6.*"
meson = "1.2.3.*"
pkgconfig = "1.5.5.*"
